name: Service
definition: Information about software programs that run in the background and typically start with the operating system.
collection_layers:
  - host
platforms:
  - Windows
  - Linux
  - MacOS
contributors: 
  - ATT&CK
  - CTID
data_components:
  - name: service attributes
    type: information
    description: Service-specific attributes, such as start type.
    relationships:
      - source_data_element: process
        relationship: modified
        target_data_element: service attributes
  - name: service context
    type: information
    description: General information around services.
    relationships:
      - source_data_element: service
        relationship: started
        target_data_element: 
      - source_data_element: service
        relationship: stopped
        target_data_element: 
  - name: service creation
    type: activity
    description: A new service/daemon is created.
    relationships:
      - source_data_element: user
        relationship: created
        target_data_element: service
  - name: service access
    type: activity
    description: A service/daemon was opened or accessed.
    relationships:
      - source_data_element: user
        relationship: requested access
        target_data_element: service
  - name: service modification
    type: activity
    description: A service/daemon was modified.
    relationships:
      - source_data_element: process
        relationship: modified
        target_data_element: service
references:
  - https://docs.microsoft.com/en-us/dotnet/framework/windows-services/introduction-to-windows-service-applications
  - https://www.linux.com/news/introduction-services-runlevels-and-rcd-scripts/